# Site settings
title: The Podlets - A Cloud Native Podcast
tagline: Exploring cloud native, one buzzword at a time!
email:
author: The Podlets Authors
description: Cloud native technologies have unique elements. In the greater tech community, there is not only a lack of knowledge of concepts and certain technologies, but also misunderstanding and almost mysticism surrounding the space. The Podlets show aims to elucidate and demystify these elements to help people confidently embrace cloud native technology.
url: https://thepodlets.io
logo: podlets-logo.png
twitter:
  username: thepodlets
  card: summary
vm_logo: vm-logo.png
gh_repo: https://github.com/vmware/Kubelets/
hero: 
  background-color: white
footer:
  title: Getting Started
  content: To help you get started, see the documentation.
  cta_title: 
  cta_url: /docs/main
  cta_text: Documentation
  vm-link: http://vmware.github.io/
podcast: the-podlets
footer_social_links:
  Google Play:
    fa_icon: -icon google-play
    url: https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Ianjullnevrto5lxvcfxtbuvx74?
  Twitter:
    fa_icon: fab fa-twitter
    url: https://twitter.com/thepodlets
  iTunes:
    fa_icon: -icon itunes
    url: https://podcasts.apple.com/us/podcast/the-podlets-podcast/id1488167284
  Spotify:
    fa_icon: fab fa-spotify
    url: https://open.spotify.com/show/3ad8E1z4rYMPqUYCLRVBSG
  RSS:
    fa_icon: fa fa-rss
    url: https://www.omnycontent.com/d/playlist/3451a52d-88b7-400a-9a02-aa610027e5d0/6662044f-706b-4890-a3f8-aa9a0004642b/bf774da5-66a7-4b5d-b0e9-aa9a0004aa39/podcast.rss
# used for the common "Listen & Watch" links throughout the site.
podcast_links:
  primary:
  - icon: youtube 
    url: https://www.youtube.com/playlist?list=PL7bmigfV0EqSh-btGOy8BLG3lsF0ylfZ-
    alt: YouTube
  - icon: itunes
    url: https://podcasts.apple.com/us/podcast/the-podlets-podcast/id1488167284
    alt: iTunes
  - icon: spotify
    url: https://open.spotify.com/show/3ad8E1z4rYMPqUYCLRVBSG
    alt: Spotify
  secondary:
  - icon: overcast
    url: https://overcast.fm/itunes1488167284/the-podlets-podcast
    alt: Overcast
  - icon: google-podcasts
    url: https://www.google.com/podcasts?feed=aHR0cHM6Ly93d3cub21ueWNvbnRlbnQuY29tL2QvcGxheWxpc3QvMzQ1MWE1MmQtODhiNy00MDBhLTlhMDItYWE2MTAwMjdlNWQwLzY2NjIwNDRmLTcwNmItNDg5MC1hM2Y4LWFhOWEwMDA0NjQyYi9iZjc3NGRhNS02NmE3LTRiNWQtYjBlOS1hYTlhMDAwNGFhMzkvcG9kY2FzdC5yc3M%3d
    alt: Google Podcasts
  - icon: stitcher
    url: https://www.stitcher.com/podcast/the-podlets
    alt: Stitcher
  - icon: google-play
    url: https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Ianjullnevrto5lxvcfxtbuvx74?
    alt: Google Play
  tertiary: 
  - icon: twitter-lg
    url: https://twitter.com/thepodlets
    alt: Twitter
  - icon: rss-lg
    url: https://www.omnycontent.com/d/playlist/3451a52d-88b7-400a-9a02-aa610027e5d0/6662044f-706b-4890-a3f8-aa9a0004642b/bf774da5-66a7-4b5d-b0e9-aa9a0004aa39/podcast.rss
    alt: RSS
  - icon: github
    url: https://github.com/vmware-tanzu/thepodlets
    alt: Github
# assign highlighted episodes here by episode ID. limited to 3 on home page, selected from the top down.
# also appears on the about page.
highlighted: 
- 007-kubernetes-as-per-kelsey-hightower
- 006-a-conversation-with-joe-beda
- 005-cloud-native-infrastructure  

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" 
    values:
      layout: "posts"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "episodes" 
    values:
      layout: "episodes"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  episodes:
    output: true
  hosts:
    output: false

# Build settings
permalink: :title/
sass:
  sass_dir: css
  style: :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-relative-links # Used to auto generate md links to html links
  - jekyll-optional-front-matter # Parse Markdown files that do not have front-matter callouts
  - jekyll-readme-index # use README.md as index.html
  - jekyll-titles-from-headings # pull the page title from the first Markdown heading when none is specified.
  - jekyll-paginate # pagination object for collections (e.g. posts)
  - jekyll-seo-tag


# Include these subdirectories
include: 
  - CONTRIBUTING.md
  - README.md

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README-JEKYLL.md
  - README-Podlets.md
  - LICENSE
  - CNAME
  - Runbook.docx
  - '*.sh'